### ISSUE TITLE
Please add a screenshot

### ISSUE THREAD

**Issue by unixorn** [xremix/oh-my-zsh-xremix-theme#1]
Please add a screenshot so people can see what the theme looks like before cloning it.

**Comment by xremix** [comment]
Thank you for that great idea @unixorn, I added one.

**Comment by unixorn** [comment]
Cool! I've added your theme to the [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) list.

**Comment by xremix** [comment]
Awesome thank you @unixorn
